### ISSUE TITLE
Processing ./wheelhouse/python-dateutil-2.7.0.tar.gz fails in charm software installation

### ISSUE THREAD

**Issue by jamesbeedy** [juju-solutions/layer-basic#110]
Hitting this https://paste.ubuntu.com/p/Jc7DTKSjbg/ on all charms that pull in python-dateutil as a dependency of something in wheelhouse.txt.

**Comment by johnsca** [comment]
For the record, this is apparently due to pip not picking up on dependencies that are listed in `setup_requires` rather than `install_requires` to add them to the wheelhouse, and may well be resolved in pip 10 when that becomes available.  Technically, this could affect packages other than setuptools, but that definitely seems like it would be the most common case where this would be encountered by far.

Ref:
* https://github.com/pypa/pypi-legacy/issues/322#issuecomment-293033220
* https://github.com/pytest-dev/pytest-xdist/issues/136
* https://www.python.org/dev/peps/pep-0518/
