### ISSUE TITLE
Magic imports added to lib/charms/layer

### ISSUE THREAD

**Issue by stub42** [juju-solutions/layer-basic#120]
Magic import logic has been added to lib/charms/layer, which stops this namespace working like a standard Python package. It seems to be there as a convenience. It is technically a backwards incompatible change as it changes import order, causes imports of files that should not necessarily be imports (eg. conditional imports, such as only importing a module after its dependencies are installed), and seems an unnecessary support burden as we will need to keep this behavior indefinitely.

Perhaps we shouldn't be recommending lib/charms/layer as a shared area for layers to use, as it requires everyone to play by the same rules and remain backwards compatible (which is hard, since you don't know what behavior others are relying on). Layers can use their own distinct namespace like normal Python packages do.

**Comment by stub42** [comment]
Its been there since April so I guess its too late to change it. I'm not going to be allowing the suggested syntax though (from charms import layer; layer.foo.baz()), as I believe it will cause trouble with linters and test harnesses.

**Comment by johnsca** [comment]
I don't think import order was ever particularly well-defined and shouldn't really be depended on.

I'm confused about `charms.layer` not working as a namespace.  There has pretty much always been a `lib/charms/layer/__init__.py` file, so I don't see why doing preemptive imports would change anything there.  I do think it fails with external packages that are placed under the `charms.layer` namespace, but are you saying that it previously worked somehow?

I hadn't considered the use-case of the layer's lib having dependencies that aren't satisfied by the time the bootstrap is finished.  TBH, I think that would be a bad pattern to use, at least at the module level; if you wanted to have some features driven by runtime conditions, I would expect those to be wrapped within functions or nested submodules, so that the lib for the layer itself can always be imported.

My original intention with this change, and with the original inception of the `charms.layer` namespace is to encourage a convention that makes it easy to see when a particular function call is coming from a particular layer and to reduce the possibility of naming conflicts between layers.  However, before this change, the way imports worked meant that getting something like `layer.foo.func()` to work would require duplicate import lines like:

```python
import charms.layer.foo
from charms import layer
```

Because of that, almost everyone instead did:

```python
from charms.layer import foo
```

Which was mostly ok but within the same layer often (at least in my experience) led to name conflicts, as the name of the layer itself was frequently the best choice for some function or variable, or the layer itself was named after some library that was used within it.

Since it's just a convention, as you noted charms are free to eschew it.  However, I find it leads to easier to read layer and charm code, personally.

Also, I would be surprised if a linter did complain about `layer.foo.baz()` as that's fairly common in Python code, from my experience.
