### ISSUE TITLE
Improve Travis log output, particularly on the functional tests

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-basic#161]
Originally discussed in #160, the logging on the functional tests for Travis is more verbose than it needs to be primarily to avoid timeout issues from slow clouds due to no output within 10 minutes.  As an alternative, we could use [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) to wrap the commands that can be slow.  Additionally, having too much logging could cause [Travis to kill the job](https://docs.travis-ci.com/user/common-build-problems/#log-length-exceeded) anyway.  In that vein, we should also consider modifying the `after_failure` section to not dump unit logs for units not in an error state.

We could also use [folding](https://github.com/travis-ci/travis-ci/issues/2285#issuecomment-42724719) to make the log easier to read in general.

**Comment by fnordahl** [comment]
I think I did have a go at the ``travis_wait`` approach, but the sudo back to the travis user trick to activate the LXD group to access the LXD socket clobbers with it.

In some other repositories I have changed permissions on the LXD socket instead of doing the sudo trick and we can have a go at that to see if that plays nice with the travis_wait.

**Comment by johnsca** [comment]
+1 to the socket permission approach.

It's also worth noting that the `after_failure` section is already automatically folded and you can't nest folds, so my original thought of putting each unit's log into its own fold can't be done.  But I think skipping logs for non-error units would be better anyway.
