### ISSUE TITLE
Bootstrap moved without deprecation, all existing layers with hooks broken

### ISSUE THREAD

**Issue by stub42** [juju-solutions/layer-basic#35]
The bootstrap code was moved to lib/charms/layer and the hook template altered. A link was not left to the original path though, so all existing layers with their (now out of date) hooks should fail. A second bug in charm-tools hides this, where lib/charms/bootstrap.py is not removed on 'charm build' so broken layers may remain oblivious for some time.

**Comment by johnsca** [comment]
The hook code should be updated on charm build to reflect the move, which is the behavior I'm seeing.  Are you seeing the old hook code being left?

**Comment by stub42** [comment]
The hooks embedded in my charm and layers were not replaced or updated by charm build. The only updated hooks I saw were from the base layer.

**Comment by johnsca** [comment]
Well that makes sense.  What hooks is layer-basic missing that you need to have embedded manually?  

Perhaps we need to rush to get juju/charm-tools#98 implemented before the cut-off for charm-tools going into the archive for xenial?

**Comment by stub42** [comment]
leader-elected, leader-settings-changed (from the leadership layer). coordinator-relation-changed, coordinator-relation-departed (from the coordinator layer). And all the PG ones - {db,db-admin,data,syslog,nrpe_external_master,local_monitors,master,replication}-relation-{changed,departed}

Yes, I think generating hooks is the best way of stopping this happening again. Right now, it probably isn't worth patching backwards compatibility as I suspect there are no layers in use yet that haven't been fixed already or used by a charmer without ability to fix them.

**Comment by johnsca** [comment]
All of these should already be provided by the base layer / build process, though.  The leadership layer could have the hooks removed; I think those are a hold-over from before they were included in this layer.  And all relation hooks should be generated from the template during build.

**Comment by stub42** [comment]
I don't get relation hooks generated. Are these introspected from reactive.relations.RelationBase, which I do not use for most of my relations?

**Comment by johnsca** [comment]
They're generated for any interface layer included in `layer.yaml`.  Why are you not using those?

**Comment by stub42** [comment]
None of the interfaces exist, and several will never exist as the only implementation ever will be in the charm. The implementations have come from legacy, non-reactive code. My attempts at moving these server side relations to RelationBase style code have all failed (apart from syslog), ending up with more confusing and less maintainable code. So, for now at least, its all done with standard reactive handlers. This is a journey :)

I don't know if it is my inexperience with this part of the reactive framework, or if I need a better RelationBase. In particular, it seems cumbersome, and the conversation metaphor does match my understanding of Juju relations (which are not peer to peer, but broadcast), and refers to the local end of the relation as remote which really jars when mixed with code using the traditional model where you have your local end of the relation and each of your peers and the remote units each have their own remote end. It also doesn't seem to have the concept of your peers on the relation, which is critical for the client interfaces where standby units need to mirror data from the master unit and rebroadcast it to the client units (which is triggered by the master 'pinging' the other units on the peer relation, making a standalone implementation layer difficult as it is necessarily entwined with a peer relation).

**Comment by johnsca** [comment]
I acknowledge that the conversation metaphor doesn't exactly match the reality of how relation data works, but the metaphor was chosen specifically to encourage the development of more "interactive" interface protocols&mdash;that is, protocols that had more of a sense of negotiating a concensus than just broadcasting data.  It's certainly not a perfect metaphor, and I'd be happy to work with you on [charms.reactive](https://github.com/juju-solutions/charms.reactive) to explore an alternative implementation or subclass(es) of RelationBase that handle the lower-level communication differently, with different metaphors that match your mental model or use-case better.

However, the real purpose of interface layers is to  abstract, and provide a concrete, shared implementation of, that communication by providing a defined API describing the *intent* of the interface.  Really, it's two APIs: one between the providing charm and the interface layer, and one between the requiring charm and the interface layer, each tailored to the needs of that charm.  And any complexity of the communication protocol itself&mdash;the details of exactly how that intent is translated into data and how that data is communicated between the two ends&mdash;especially complexity due to legacy concerns from previous implementations, should be encapsulated by the interface layer and hidden from both sides.  By rejecting interface layers entirely, you make things harder on yourself as well as the charmers that want to interact with your charm.

But, regarding this issue, I don't think it's a bug with this layer, since your layers are what overrode or didn't make use of the hooks that are provided by this layer.

**Comment by stub42** [comment]
The bug is best solved by juju/charm-tools#98 . Until that is implemented, layers will sometimes need to embed snapshots of hooks.template from the basic layer. If backwards incompatible changes are made to the basic layer, such as moving the location of the bootstrap method without providing an alias in the old location, these other layers all break. I don't think there is anything to worry about this time, as a quick click though of the available layers shows I'm the only one affected ;)

And I haven't given up on interfaces or RelationBase. I agree concrete, shared implementations are needed which is why I hope to shortly fix the pgsql interface. On the server side, which in most cases never needs to be shared, it is less clear. But I'll certainly use RelationBase on the server end if I can make code clearer and more maintainable. It might even go in a separate interface branch if that doesn't reduce agility.
